### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by ghost**
Hi Daniel,

Firstly, thank you for the effort you put into explaining your answer on stack http://stackoverflow.com/a/28220242/1951992

I have been picking apart the code you wrote, to better understand VisualEffectViews and Swift.  When I finally figured it out, I realised I had moved your code around a bit.

I figured it would be worth contributing this back, if your happy to accept?  No worries otherwise.

Thanks
Rob

### CODE REVIEW

**Comment by danielgalasko** [comment]
Hi @robdashnash, thanks for contributing! Great to see that this has helped people. 

I looked through your commit and the benefits of it aren't immediately obvious. From what I understand you want to remove the Blurred View subclass and simply move all that code into the Table View. I'm not sure why this is necessary?

**Comment by ghost** [comment]
It's just less lines of code is all

**Comment by danielgalasko** [comment]
@robdashnash I see, I guess what I'm getting at is that I prefer having view specific code in a UIView subclass. Otherwise we end up with massive view controller's. Which is not exactly the case in this example but I'm hoping to encourage that understanding in newcomers. So the idea is that it makes sense to encapsulate a UIView instance that manages a blurred UIImageView, and all the View Controller does is use this view as a background view...

Perhaps I could change the name of the view but as far as I'm concerned I prefer separation of concerns over less LOC :)

**Comment by ghost** [comment]
I basically changed your code so that the following was the focus; emphasising the point you was trying to explain in your post on stacks.

'''
let backgroundView = UIView(frame: view.bounds)
backgroundView.autoresizingMask = resizingMask
backgroundView.addSubview(self.buildImageView())
backgroundView.addSubview(self.buildBlurView())
tableView.backgroundView = backgroundView
'''

It seemed suitable to have this front and centre in your view controller, just to get to the point.

I agree encapsulation is good for code re-use and maintenance.  But only for projects right?  Let's not use a commercial sense of strategy for an endeavour that we aren't going to persue.

**Comment by danielgalasko** [comment]
I apologise for the delay. I looked at the project again and I think you have a really valid point. There was too much noise in my implementation of the BackgroundBlurView and I agree the source file separation is not really needed. I have refactored it and moved the BlurView into the tableView and cleaned it up significantly! But I still like building the background inside a custom UIView subclass rather than as separate View Controller methods. Thanks for your contribution!

**Comment by danielgalasko** [comment]
closing from a92078a00dfb4717130d189947ec08c4fd160d66

**Pull request closed without merging**
